### Recuperar las peliculas de un usuario por id de usuario

GET http://localhost:4000/api/users/1/movies


### Recuperar todas las peliculas

GET http://localhost:4000/api/movies

### Recuperar una pelicula por ID

GET http://localhost:4000/api/movies/1

### Recuperar generos de peliculas por ID

GET http://localhost:4000/api/movies/1/genres

### Recuperar peliculas con sus generos

GET http://localhost:4000/api/movies-genres

### Recuperar pelicula con sus generos por nombre

GET http://localhost:4000/api/movies-genres/Inception

### Recuperar generos de peliculas

GET http://localhost:4000/api/genres

### Recuperar una peliculas y generos

GET http://localhost:4000/api/movies-genres

### Recuperar todos los usuarios

GET http://localhost:4000/api/users

### Recuperar todos los usuarios con sus peliculas

GET http://localhost:4000/api/users-movies

### Recuperar peliculas por genero

GET https://movies-server-2kuw.onrender.com/api/movies/genres/3

### Agregar una pelicula

POST http://localhost:4000/api/movies
Content-Type: application/json

{
    "nombre": "Forrest Gump",
    "director": "Robert Zemeckis",
    "anio": 1994,
    "imagen": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSgJaxEFJxdwh2SP1sAI92IQgaThjvJM6XSd1G2YEEqVwjqNnVF",
    "duracion": "142"
}

### Eliminar una pelicula

DELETE http://localhost:4000/api/movies/3

### Actualizar una pelicula

PUT http://localhost:4000/api/movies/1
Content-Type: application/json

{
    "nombre": "Titanic",
    "director": "James Cameron",
    "anio": 1997,
    "imagen": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTO4uDn64PLOGg3ECiPApplZ_SI6n3ZTGYfQLxYpA1GeFPxYqaT",
    "duracion": "195"
}


### Agregar un usuario
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "email": "miguelote@gmail.com",
    "nombre_usuario": "miguelote04",
    "contraseña": "abc123"
}

### Iniciar sesion

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "nombre_usuario": "lore123",
    "contraseña": "lore123"
}

### Agregar una pelicula a un usuario

POST http://localhost:4000/api/users-movies
Content-Type: application/json

{
    "id_usuario": 7,
    "id_pelicula": 14
}

### Devolver una pelicula de un usuario

GET http://localhost:4000/api/users-movies/1/18

### Eliminar una pelicula de un usuario

DELETE http://localhost:4000/api/users-movies/8/1
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmVfdXN1YXJpbyI6Im5pY29sYXMwIiwiaWQiOjEyLCJpYXQiOjE3MTM2MzI4NTUsImV4cCI6MTcxMzYzNjQ1NX0.LpGEbLNGGefeW7-LyqDfIDmiPkUx7vrRb2q5euHiFOU"